<?php

// Composer: "fzaninotto/faker": "v1.3.0"
//use Faker\Factory as Faker;

class BordersTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		 DB::table('borders')->delete();

		$items = array(
// Rectagles
['cat_id'=>'1', 'size_id'=>'1','name'=>'1/4 Sheet Photo Image', 'description'=>'1/4 Sheet 10x7.5', 'file'=>'10x7_5.png', 'make'=>'1'],
['cat_id'=>'1', 'size_id'=>'2','name'=>'Logo Edible Cake Image', 'description'=>'8x6 inch edible image', 'file'=>'8x6.png', 'make'=>'1'],
['cat_id'=>'1', 'size_id'=>'3','name'=>'Middle Image Photo Cake', 'description'=>'6x4.5 inch edible image', 'file'=>'6x4_5.png', 'make'=>'1'],
// Circles
['cat_id'=>'2', 'size_id'=>'4','name'=>'7 inch edible image', 'description'=>'7 Inch round edible cake image', 'file'=>'7inch.png', 'make'=>'1'],
['cat_id'=>'2', 'size_id'=>'5','name'=>'6 inch edible image', 'description'=>'6 Inch round edible cake image', 'file'=>'6inch.png', 'make'=>'1'],
['cat_id'=>'2', 'size_id'=>'6','name'=>'5 inch edible image', 'description'=>'5 Inch round edible cake image', 'file'=>'5inch.png', 'make'=>'1'],
// Cupcakes
['cat_id'=>'3', 'size_id'=>'12','name'=>'12 2 Inch Edible Images', 'description'=>'7 Inch round edible cake image', 'file'=>'12-2inch.png', 'make'=>'12'],
['cat_id'=>'3', 'size_id'=>'1','name'=>'8 2.5 Inch Edible Images', 'description'=>'6 Inch round edible cake image', 'file'=>'8-2_5inch.png', 'make'=>'8'],
['cat_id'=>'3', 'size_id'=>'1','name'=>'24 1.5 Inch Edible Images', 'description'=>'5 Inch round edible cake image', 'file'=>'24-1_5inch.png', 'make'=>'24'],
// Birthday Rectangles
['cat_id'=>'4', 'size_id'=>'1','name'=>'Balloons', 'description'=>'Birthday Border 1', 'file'=>'1.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Happy Balloons', 'description'=>'Birthday Border 2', 'file'=>'2.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Fiesta Balloons', 'description'=>'Birthday Border 3', 'file'=>'3.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Kids Balloons', 'description'=>'Birthday Border 4', 'file'=>'4.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'5.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'6.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'7.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'8.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'9.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'10.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'11.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'12.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'13.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'14.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'15.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'16.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'17.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'18.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'19.png', 'make'=>'1'],
['cat_id'=>'4', 'size_id'=>'1','name'=>'Party Balloons', 'description'=>'Birthday Border 5', 'file'=>'20.png', 'make'=>'1'],
// Action Rectangles
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 1', 'file'=>'21.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 2', 'file'=>'22.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 3', 'file'=>'23.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 4', 'file'=>'24.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'25.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'26.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'27.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'28.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'29.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'30.png', 'make'=>'1'],
['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'31.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'32.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'33.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'34.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'35.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'36.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'37.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'38.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'39.png', 'make'=>'1'],
// ['cat_id'=>'5', 'size_id'=>'1','name'=>'Action', 'description'=>'Birthday Border 5', 'file'=>'40.png', 'make'=>'1'],

// Super Heroes Rectangles
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 1', 'file'=>'41.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 2', 'file'=>'42.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 3', 'file'=>'43.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 4', 'file'=>'44.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'45.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'46.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'47.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'48.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'49.png', 'make'=>'1'],
['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'50.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'51.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'52.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'53.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'54.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'55.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'56.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'57.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'58.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'59.png', 'make'=>'1'],
// ['cat_id'=>'6', 'size_id'=>'1','name'=>'Super Heroes', 'description'=>'Birthday Border 5', 'file'=>'60.png', 'make'=>'1'],

// Anniversary Rectangles
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 1', 'file'=>'61.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 2', 'file'=>'62.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 3', 'file'=>'63.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 4', 'file'=>'64.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'65.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'66.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'67.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'68.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'69.png', 'make'=>'1'],
['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'70.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'71.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'72.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'73.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'74.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'75.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'76.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'77.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'78.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'79.png', 'make'=>'1'],
// ['cat_id'=>'7', 'size_id'=>'1','name'=>'Anniversary', 'description'=>'Birthday Border 5', 'file'=>'80.png', 'make'=>'1'],

// Halloween Rectangles
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 1', 'file'=>'81.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 2', 'file'=>'82.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 3', 'file'=>'83.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 4', 'file'=>'84.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'85.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'86.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'87.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'88.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'89.png', 'make'=>'1'],
['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'90.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'91.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'92.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'93.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'94.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'95.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'96.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'97.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'98.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'99.png', 'make'=>'1'],
// ['cat_id'=>'8', 'size_id'=>'1','name'=>'Holloween', 'description'=>'Birthday Border 5', 'file'=>'100.png', 'make'=>'1'],


// Christmas Rectangles
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 1', 'file'=>'101.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 2', 'file'=>'102.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 3', 'file'=>'103.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 4', 'file'=>'104.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'105.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'106.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'107.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'108.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'109.png', 'make'=>'1'],
['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'110.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'111.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'112.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'113.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'114.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'115.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'116.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'117.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'118.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'119.png', 'make'=>'1'],
// ['cat_id'=>'9', 'size_id'=>'1','name'=>'Christmas', 'description'=>'Birthday Border 5', 'file'=>'120.png', 'make'=>'1'],


// Valentines Rectangles
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 1', 'file'=>'121.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 2', 'file'=>'122.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 3', 'file'=>'123.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 4', 'file'=>'124.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'125.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'126.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'127.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'128.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'129.png', 'make'=>'1'],
['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'130.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'131.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'132.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'133.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'134.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'135.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'136.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'137.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'138.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'139.png', 'make'=>'1'],
// ['cat_id'=>'10', 'size_id'=>'1','name'=>'Valentines', 'description'=>'Birthday Border 5', 'file'=>'140.png', 'make'=>'1'],


// Easter Rectangles
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 1', 'file'=>'141.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 2', 'file'=>'142.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 3', 'file'=>'143.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 4', 'file'=>'144.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'145.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'146.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'147.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'148.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'149.png', 'make'=>'1'],
['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'150.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'151.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'152.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'153.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'154.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'155.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'156.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'157.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'158.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'159.png', 'make'=>'1'],
// ['cat_id'=>'11', 'size_id'=>'1','name'=>'Easter', 'description'=>'Birthday Border 5', 'file'=>'160.png', 'make'=>'1'],

// Magazine Rectangles
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 1', 'file'=>'161.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 2', 'file'=>'162.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 3', 'file'=>'163.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 4', 'file'=>'164.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'165.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'166.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'167.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'168.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'169.png', 'make'=>'1'],
['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'170.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'171.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'172.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'173.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'174.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'175.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'176.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'177.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'178.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'179.png', 'make'=>'1'],
// ['cat_id'=>'12', 'size_id'=>'1','name'=>'Magazine', 'description'=>'Birthday Border 5', 'file'=>'180.png', 'make'=>'1'],

// Celebrities Rectangles
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 1', 'file'=>'181.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 2', 'file'=>'182.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 3', 'file'=>'183.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 4', 'file'=>'184.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'185.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'186.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'187.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'188.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'189.png', 'make'=>'1'],
['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'190.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'191.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'192.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'193.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'194.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'195.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'196.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'197.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'198.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'199.png', 'make'=>'1'],
// ['cat_id'=>'13', 'size_id'=>'1','name'=>'Celebrities', 'description'=>'Birthday Border 5', 'file'=>'200.png', 'make'=>'1'],


// Baby Shower Rectangles
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 1', 'file'=>'201.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 2', 'file'=>'202.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 3', 'file'=>'203.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 4', 'file'=>'204.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'205.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'206.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'207.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'208.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'209.png', 'make'=>'1'],
['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'210.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'211.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'212.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'213.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'214.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'215.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'216.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'217.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'218.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'219.png', 'make'=>'1'],
// ['cat_id'=>'14', 'size_id'=>'1','name'=>'Baby Shower', 'description'=>'Birthday Border 5', 'file'=>'220.png', 'make'=>'1'],


// Graduation Rectangles
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 1', 'file'=>'221.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 2', 'file'=>'222.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 3', 'file'=>'223.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 4', 'file'=>'224.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'225.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'226.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'227.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'228.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'229.png', 'make'=>'1'],
['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'230.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'231.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'232.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'233.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'234.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'235.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'236.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'237.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'238.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'239.png', 'make'=>'1'],
// ['cat_id'=>'15', 'size_id'=>'1','name'=>'Graduation', 'description'=>'Birthday Border 5', 'file'=>'240.png', 'make'=>'1'],

// Wedding Rectangles
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 1', 'file'=>'241.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 2', 'file'=>'242.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 3', 'file'=>'243.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 4', 'file'=>'244.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'245.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'246.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'247.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'248.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'249.png', 'make'=>'1'],
['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'250.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'251.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'252.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'253.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'254.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'255.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'256.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'257.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'258.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'259.png', 'make'=>'1'],
// ['cat_id'=>'16', 'size_id'=>'1','name'=>'Wedding', 'description'=>'Birthday Border 5', 'file'=>'260.png', 'make'=>'1'],

// Princess Rectangles
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 1', 'file'=>'261.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 2', 'file'=>'262.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 3', 'file'=>'263.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 4', 'file'=>'264.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'265.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'266.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'267.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'268.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'269.png', 'make'=>'1'],
['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'270.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'271.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'272.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'273.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'274.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'275.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'276.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'277.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'278.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'279.png', 'make'=>'1'],
// ['cat_id'=>'17', 'size_id'=>'1','name'=>'Princess', 'description'=>'Birthday Border 5', 'file'=>'280.png', 'make'=>'1'],


// Sports Rectangles
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 1', 'file'=>'281.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 2', 'file'=>'282.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 3', 'file'=>'283.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 4', 'file'=>'284.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'285.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'286.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'287.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'288.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'289.png', 'make'=>'1'],
['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'290.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'291.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'292.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'293.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'294.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'295.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'296.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'297.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'298.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'299.png', 'make'=>'1'],
// ['cat_id'=>'18', 'size_id'=>'1','name'=>'Sports', 'description'=>'Birthday Border 5', 'file'=>'300.png', 'make'=>'1'],

// Casino Rectangles
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 1', 'file'=>'301.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 2', 'file'=>'302.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 3', 'file'=>'303.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 4', 'file'=>'304.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'305.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'306.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'307.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'308.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'309.png', 'make'=>'1'],
['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'310.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'311.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'312.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'313.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'314.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'315.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'316.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'317.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'318.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'319.png', 'make'=>'1'],
// ['cat_id'=>'19', 'size_id'=>'1','name'=>'Casino', 'description'=>'Birthday Border 5', 'file'=>'320.png', 'make'=>'1'],

// Animals Rectangles
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 1', 'file'=>'321.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 2', 'file'=>'322.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 3', 'file'=>'323.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 4', 'file'=>'324.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'325.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'326.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'327.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'328.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'329.png', 'make'=>'1'],
['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'330.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'331.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'332.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'333.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'334.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'335.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'336.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'337.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'338.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'339.png', 'make'=>'1'],
// ['cat_id'=>'20', 'size_id'=>'1','name'=>'Animals', 'description'=>'Birthday Border 5', 'file'=>'340.png', 'make'=>'1'],


// Fashion Rectangles
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 1', 'file'=>'341.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 2', 'file'=>'342.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 3', 'file'=>'343.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 4', 'file'=>'344.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'345.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'346.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'347.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'348.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'349.png', 'make'=>'1'],
['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'350.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'351.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'352.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'353.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'354.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'355.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'356.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'357.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'358.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'359.png', 'make'=>'1'],
// ['cat_id'=>'21', 'size_id'=>'1','name'=>'Fashion', 'description'=>'Birthday Border 5', 'file'=>'360.png', 'make'=>'1'],


// Fantasy Rectangles
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 1', 'file'=>'361.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 2', 'file'=>'362.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 3', 'file'=>'363.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 4', 'file'=>'364.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'365.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'366.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'367.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'368.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'369.png', 'make'=>'1'],
['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'370.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'371.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'372.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'373.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'374.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'375.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'376.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'377.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'378.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'379.png', 'make'=>'1'],
// ['cat_id'=>'22', 'size_id'=>'1','name'=>'Fantasy', 'description'=>'Birthday Border 5', 'file'=>'380.png', 'make'=>'1'],

// Vintage Rectangles
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 1', 'file'=>'381.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 2', 'file'=>'382.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 3', 'file'=>'383.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 4', 'file'=>'384.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'385.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'386.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'387.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'388.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'389.png', 'make'=>'1'],
['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'390.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'391.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'392.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'393.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'394.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'395.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'396.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'397.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'398.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'399.png', 'make'=>'1'],
// ['cat_id'=>'23', 'size_id'=>'1','name'=>'Vintage', 'description'=>'Birthday Border 5', 'file'=>'400.png', 'make'=>'1'],

// Candy Rectangles
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 1', 'file'=>'401.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 2', 'file'=>'402.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 3', 'file'=>'403.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 4', 'file'=>'404.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'405.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'406.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'407.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'408.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'409.png', 'make'=>'1'],
['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'410.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'411.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'412.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'413.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'414.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'415.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'416.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'417.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'418.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'419.png', 'make'=>'1'],
// ['cat_id'=>'24', 'size_id'=>'1','name'=>'Candy', 'description'=>'Birthday Border 5', 'file'=>'420.png', 'make'=>'1'],

// Pastries Rectangles
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 1', 'file'=>'421.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 2', 'file'=>'422.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 3', 'file'=>'423.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 4', 'file'=>'424.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'425.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'426.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'427.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'428.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'429.png', 'make'=>'1'],
['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'430.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'431.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'432.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'433.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'434.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'435.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'436.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'437.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'438.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'439.png', 'make'=>'1'],
// ['cat_id'=>'25', 'size_id'=>'1','name'=>'Pastries', 'description'=>'Birthday Border 5', 'file'=>'440.png', 'make'=>'1'],

// Robots Rectangles
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 1', 'file'=>'441.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 2', 'file'=>'442.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 3', 'file'=>'443.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 4', 'file'=>'444.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'445.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'446.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'447.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'448.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'449.png', 'make'=>'1'],
['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'450.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'451.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'452.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'453.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'454.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'455.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'456.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'457.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'458.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'459.png', 'make'=>'1'],
// ['cat_id'=>'26', 'size_id'=>'1','name'=>'Robots', 'description'=>'Birthday Border 5', 'file'=>'460.png', 'make'=>'1'],


// Movies Rectangles
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 1', 'file'=>'461.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 2', 'file'=>'462.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 3', 'file'=>'463.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 4', 'file'=>'464.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'465.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'466.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'467.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'468.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'469.png', 'make'=>'1'],
['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'470.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'471.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'472.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'473.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'474.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'475.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'476.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'477.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'478.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'479.png', 'make'=>'1'],
// ['cat_id'=>'27', 'size_id'=>'1','name'=>'Movies', 'description'=>'Birthday Border 5', 'file'=>'480.png', 'make'=>'1'],

// Music Rectangles
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 1', 'file'=>'481.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 2', 'file'=>'482.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 3', 'file'=>'483.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 4', 'file'=>'484.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'485.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'486.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'487.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'488.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'489.png', 'make'=>'1'],
['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'490.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'491.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'492.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'493.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'494.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'495.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'496.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'497.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'498.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'499.png', 'make'=>'1'],
// ['cat_id'=>'28', 'size_id'=>'1','name'=>'Music', 'description'=>'Birthday Border 5', 'file'=>'500.png', 'make'=>'1'],


// Technology Rectangles
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 1', 'file'=>'501.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 2', 'file'=>'502.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 3', 'file'=>'503.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 4', 'file'=>'504.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'505.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'506.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'507.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'508.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'509.png', 'make'=>'1'],
['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'510.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'511.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'512.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'513.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'514.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'515.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'516.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'517.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'518.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'519.png', 'make'=>'1'],
// ['cat_id'=>'29', 'size_id'=>'1','name'=>'Technology', 'description'=>'Birthday Border 5', 'file'=>'520.png', 'make'=>'1'],

// Dinosaurs Rectangles
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 1', 'file'=>'521.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 2', 'file'=>'522.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 3', 'file'=>'523.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 4', 'file'=>'524.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'525.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'526.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'527.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'528.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'529.png', 'make'=>'1'],
['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'530.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'531.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'532.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'533.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'534.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'535.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'536.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'537.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'538.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'539.png', 'make'=>'1'],
// ['cat_id'=>'30', 'size_id'=>'1','name'=>'Dinosaurs', 'description'=>'Birthday Border 5', 'file'=>'540.png', 'make'=>'1'],

// Websites Rectangles
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 1', 'file'=>'541.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 2', 'file'=>'542.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 3', 'file'=>'543.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 4', 'file'=>'544.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'545.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'546.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'547.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'548.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'549.png', 'make'=>'1'],
['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'550.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'551.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'552.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'553.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'554.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'555.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'556.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'557.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'558.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'559.png', 'make'=>'1'],
// ['cat_id'=>'31', 'size_id'=>'1','name'=>'Websites', 'description'=>'Birthday Border 5', 'file'=>'560.png', 'make'=>'1'],


// Cities Rectangles
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 1', 'file'=>'561.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 2', 'file'=>'562.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 3', 'file'=>'563.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 4', 'file'=>'564.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'565.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'566.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'567.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'568.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'569.png', 'make'=>'1'],
['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'570.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'571.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'572.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'573.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'574.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'575.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'576.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'577.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'578.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'579.png', 'make'=>'1'],
// ['cat_id'=>'32', 'size_id'=>'1','name'=>'Cities', 'description'=>'Birthday Border 5', 'file'=>'580.png', 'make'=>'1'],

// Video Games Rectangles
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 1', 'file'=>'581.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 2', 'file'=>'582.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 3', 'file'=>'583.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 4', 'file'=>'584.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'585.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'586.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'587.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'588.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'589.png', 'make'=>'1'],
['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'590.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'591.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'592.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'593.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'594.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'595.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'596.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'597.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'598.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'599.png', 'make'=>'1'],
// ['cat_id'=>'33', 'size_id'=>'1','name'=>'Video Games', 'description'=>'Birthday Border 5', 'file'=>'600.png', 'make'=>'1'],
		);

		// Uncomment the below to run the seeder
		 DB::table('borders')->insert($items);
	}

}