<?php

// Composer: "fzaninotto/faker": "v1.3.0"
//use Faker\Factory as Faker;

class BordersTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		 DB::table('borders')->delete();

		$items = array(


['cat_id'=>'1', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.jpg', 'name'=>'10x7.5 inch 1 rectangle piece edible cake image', 'description'=>'Edible photo decoration for cakes  for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'10x7_5.png', 'make'=>'1', 'img'=>'rectangle.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH001', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'1', 'size_id'=>'1', 'alias_name'=>'7.5x5', 'alias_img'=>'xyz.jpg', 'name'=>'7.5x5 inch 2 rectangle pieces edible cake image', 'description'=>'Edible photo decoration for cakes  and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.',  'file'=>'10x7_5.png', 'make'=>'2', 'img'=>'2-rectangle-pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH002', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'1', 'size_id'=>'1', 'alias_name'=>'5x3.7', 'alias_img'=>'xyz.jpg', 'name'=>'5x3.7 inch 4  rectangle pieces edible cake image', 'description'=>'Edible photo decoration for cakes  and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.',  'file'=>'10x7_5.png', 'make'=>'4', 'img'=>'4-rectangle-pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH003', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'1', 'size_id'=>'1', 'alias_name'=>'2.5x3.7', 'alias_img'=>'xyz.jpg', 'name'=>'2.5x3.7 inch 6 rectangle pieces edible cake image', 'description'=>'Edible photo decoration for cakes  and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.',  'file'=>'10x7_5.png', 'make'=>'6', 'img'=>'6-rectangle-pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH004', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'1', 'size_id'=>'1', 'alias_name'=>'2.5x1.8', 'alias_img'=>'xyz.jpg', 'name'=>'2.5x1.8 inch 8 rectangle pieces edible cake image', 'description'=>'Edible photo decoration for cakes  and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.',  'file'=>'10x7_5.png', 'make'=>'8', 'img'=>'8-rectangle-pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH005', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'1', 'size_id'=>'1', 'alias_name'=>'2.5x0.93', 'alias_img'=>'xyz.jpg', 'name'=>'2.5x0.93 inch 12 rectangle pieces edible cake image', 'description'=>'Edible photo decoration for cakes  and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.',  'file'=>'10x7_5.png', 'make'=>'12', 'img'=>'12-rectangle-pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH006', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'1', 'size_id'=>'1', 'alias_name'=>'2.5x0.93', 'alias_img'=>'xyz.jpg', 'name'=>'2.5x0.93 inch 24 rectangle pieces edible cake image', 'description'=>'Edible photo decoration for cakes  and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.',  'file'=>'10x7_5.png', 'make'=>'24', 'img'=>'24-rectangle-pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH007', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'2', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch round edible cake image', 'description'=>'Round edible decoration print for cakes. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'7inch.png', 'make'=>'1', 'img'=>'round.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH008', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'2', 'size_id'=>'5', 'alias_name'=>'6', 'alias_img'=>'xyz.jpg', 'name'=>'6 inch round edible cake image', 'description'=>'Round edible decoration print for cakes. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'6inch.png', 'make'=>'1', 'img'=>'six_inch_round.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH009', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'2', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 round pieces edible cake image image', 'description'=>'Round edible decoration print for cakes. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'7inch.png', 'make'=>'2', 'img'=>'2_round_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH010', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'2', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 round edible jumbo cupcke images', 'description'=>'Round edible decoration print for cakes. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'7inch.png', 'make'=>'4', 'img'=>'4_round_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH011', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'2', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 round pieces edible cookie images', 'description'=>'Round edible decoration print for cakes. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'7inch.png', 'make'=>'6', 'img'=>'6_round_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH012', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'2', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 round pieces edible size images', 'description'=>'Round edible decoration print for cakes. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'7inch.png', 'make'=>'8', 'img'=>'8_round_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH013', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'2', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 round pieces edible cupcake Images', 'description'=>'Round edible decoration print for cakes. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'7inch.png', 'make'=>'12', 'img'=>'12_round_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH014', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'2', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 round pieces edible cupcake Images', 'description'=>'Round edible decoration print for cakes. High quality edible paper (frosting sheet) printed with bright food coloring at high resolution 300 dpi.', 'file'=>'7inch.png', 'make'=>'24', 'img'=>'24_round_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH015', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'3', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch heart edible cake image', 'description'=>'Heart shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring. ', 'file'=>'7inch_heart.png', 'make'=>'1', 'img'=>'heart.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH016', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'3', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 heart pieces edible cake image image', 'description'=>'Heart shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_heart.png', 'make'=>'2', 'img'=>'2_heart_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH017', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'3', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 heart edible jumbo cupcke images', 'description'=>'Heart shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_heart.png', 'make'=>'4', 'img'=>'4_heart_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH018', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'3', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 heart pieces edible cookie images', 'description'=>'Heart shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_heart.png', 'make'=>'6', 'img'=>'6_heart_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH019', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'3', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 heart pieces edible size images', 'description'=>'Heart shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_heart.png', 'make'=>'8', 'img'=>'8_heart_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH020', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'3', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 heart pieces edible cupcake Images', 'description'=>'Heart shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_heart.png', 'make'=>'12', 'img'=>'12_heart_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH021', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'3', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 heart pieces edible cupcake Images', 'description'=>'Heart shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_heart.png', 'make'=>'24', 'img'=>'24_heart_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH022', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'4', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch star edible cake image', 'description'=>'Star shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_star.png', 'make'=>'1', 'img'=>'star.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH023', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'4', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 star pieces edible cake image image', 'description'=>'Star shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_star.png', 'make'=>'2', 'img'=>'2_star_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH024', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'4', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 star edible jumbo cupcke images', 'description'=>'Star shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_star.png', 'make'=>'4', 'img'=>'4_star_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH025', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'4', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 star pieces edible cookie images', 'description'=>'Star shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_star.png', 'make'=>'6', 'img'=>'6_star_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH026', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'4', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 star pieces edible size images', 'description'=>'Star shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_star.png', 'make'=>'8', 'img'=>'8_star_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH027', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'4', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 star pieces edible cupcake Images', 'description'=>'Star shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_star.png', 'make'=>'12', 'img'=>'12_star_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH028', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'4', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 star pieces edible cupcake Images', 'description'=>'Star shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_star.png', 'make'=>'24', 'img'=>'24_star_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH029', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'5', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch flower edible cake image', 'description'=>'Flower shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_flower.png', 'make'=>'1', 'img'=>'flower.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH030', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'5', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 flower pieces edible cake image image', 'description'=>'Flower shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_flower.png', 'make'=>'2', 'img'=>'2_flower_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH031', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'5', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 flower edible jumbo cupcke images', 'description'=>'Flower shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_flower.png', 'make'=>'4', 'img'=>'4_flower_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH032', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 flower pieces edible cookie images', 'description'=>'Flower shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_flower.png', 'make'=>'6', 'img'=>'6_flower_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH033', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 flower pieces edible size images', 'description'=>'Flower shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_flower.png', 'make'=>'8', 'img'=>'8_flower_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH034', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 flower pieces edible cupcake Images', 'description'=>'Flower shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_flower.png', 'make'=>'12', 'img'=>'12_flower_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH035', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 flower pieces edible cupcake Images', 'description'=>'Flower shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_flower.png', 'make'=>'24', 'img'=>'24_flower_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH036', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'6', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch diamond edible cake image', 'description'=>'Diamond shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_diamond.png', 'make'=>'1', 'img'=>'diamond.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH037', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'6', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 diamond pieces edible cake image image', 'description'=>'Diamond shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_diamond.png', 'make'=>'2', 'img'=>'2_diamond_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH038', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'6', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 diamond edible jumbo cupcke images', 'description'=>'Diamond shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_diamond.png', 'make'=>'4', 'img'=>'4_diamond_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH039', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'6', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 diamond pieces edible cookie images', 'description'=>'Diamond shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_diamond.png', 'make'=>'6', 'img'=>'6_diamond_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH040', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'6', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 diamond pieces edible size images', 'description'=>'Diamond shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_diamond.png', 'make'=>'8', 'img'=>'8_diamond_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH041', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'6', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 diamond pieces edible cupcake Images', 'description'=>'Diamond shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_diamond.png', 'make'=>'12', 'img'=>'12_diamond_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH042', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'6', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 diamond pieces edible cupcake Images', 'description'=>'Diamond shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_diamond.png', 'make'=>'24', 'img'=>'24_diamond_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH043', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'7', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch emblem edible cake image', 'description'=>'Emblem shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_emblem.png', 'make'=>'1', 'img'=>'emblem.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH044', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'7', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 emblem pieces edible cake image image', 'description'=>'Emblem shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_emblem.png', 'make'=>'2', 'img'=>'2_emblem_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH045', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'7', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 emblem edible jumbo cupcke images', 'description'=>'Emblem shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_emblem.png', 'make'=>'4', 'img'=>'4_emblem_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH046', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 emblem pieces edible cookie images', 'description'=>'Emblem shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_emblem.png', 'make'=>'6', 'img'=>'6_emblem_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH047', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'2.5', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 emblem pieces edible size images', 'description'=>'Emblem shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_emblem.png', 'make'=>'8', 'img'=>'8_emblem_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH048', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 emblem pieces edible cupcake Images', 'description'=>'Emblem shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_emblem.png', 'make'=>'12', 'img'=>'12_emblem_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH049', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 emblem pieces edible cupcake Images', 'description'=>'Emblem shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_emblem.png', 'make'=>'24', 'img'=>'24_emblem_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH050', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'8', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch monogram edible cake image', 'description'=>'Monogram shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_monogram.png', 'make'=>'1', 'img'=>'monogram.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH051', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'8', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 monogram pieces edible cake image image', 'description'=>'Monogram shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_monogram.png', 'make'=>'2', 'img'=>'2_monogram_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH052', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'8', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 monogram edible jumbo cupcke images', 'description'=>'Monogram shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_monogram.png', 'make'=>'4', 'img'=>'4_monogram_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH053', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 monogram pieces edible cookie images', 'description'=>'Monogram shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_monogram.png', 'make'=>'6', 'img'=>'6_monogram_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH054', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 monogram pieces edible size images', 'description'=>'Monogram shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_monogram.png', 'make'=>'8', 'img'=>'8_monogram_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH055', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 monogram pieces edible cupcake Images', 'description'=>'Monogram shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_monogram.png', 'make'=>'12', 'img'=>'12_monogram_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH056', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 monogram pieces edible cupcake Images', 'description'=>'Monogram shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_monogram.png', 'make'=>'24', 'img'=>'24_monogram_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH057', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'9', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch oval edible cake image', 'description'=>'Oval shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_oval.png', 'make'=>'1', 'img'=>'oval.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH058', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'9', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 oval pieces edible cake image image', 'description'=>'Oval shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_oval.png', 'make'=>'2', 'img'=>'2_oval_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH059', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'9', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 oval edible jumbo cupcke images', 'description'=>'Oval shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_oval.png', 'make'=>'4', 'img'=>'4_oval_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH060', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'9', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 oval pieces edible cookie images', 'description'=>'Oval shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_oval.png', 'make'=>'6', 'img'=>'6_oval_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH061', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'9', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 oval pieces edible size images', 'description'=>'Oval shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_oval.png', 'make'=>'8', 'img'=>'8_oval_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH062', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'9', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 oval pieces edible cupcake Images', 'description'=>'Oval shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_oval.png', 'make'=>'12', 'img'=>'12_oval_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH063', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'9', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 oval pieces edible cupcake Images', 'description'=>'Oval shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_oval.png', 'make'=>'24', 'img'=>'24_oval_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH064', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'10', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch square edible cake image', 'description'=>'Square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_square.png', 'make'=>'1', 'img'=>'square.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH065', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'10', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 square pieces edible cake image image', 'description'=>'Square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_square.png', 'make'=>'2', 'img'=>'2_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH066', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'10', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 square edible jumbo cupcke images', 'description'=>'Square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_square.png', 'make'=>'4', 'img'=>'4_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH067', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'10', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 square pieces edible cookie images', 'description'=>'Square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_square.png', 'make'=>'6', 'img'=>'6_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH068', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'10', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 square pieces edible size images', 'description'=>'Square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_square.png', 'make'=>'8', 'img'=>'8_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH069', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'10', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 square pieces edible cupcake Images', 'description'=>'Square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_square.png', 'make'=>'12', 'img'=>'12_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH070', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'10', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 square pieces edible cupcake Images', 'description'=>'Square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_square.png', 'make'=>'24', 'img'=>'24_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH071', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'11', 'size_id'=>'4', 'alias_name'=>'7', 'alias_img'=>'xyz.jpg', 'name'=>'7 inch round square edible cake image', 'description'=>'Round square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_round_square.png', 'make'=>'1', 'img'=>'round_square.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH072', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'11', 'size_id'=>'6', 'alias_name'=>'5', 'alias_img'=>'xyz.jpg', 'name'=>'5 inch 2 round square pieces edible cake image image', 'description'=>'Round square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_round_square.png', 'make'=>'2', 'img'=>'2_round_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH073', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'11', 'size_id'=>'12', 'alias_name'=>'3.5', 'alias_img'=>'xyz.jpg', 'name'=>'3.5 Inch 4 round square edible jumbo cupcke images', 'description'=>'Round square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_round_square.png', 'make'=>'4', 'img'=>'4_round_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH074', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'11', 'size_id'=>'1', 'alias_name'=>'3', 'alias_img'=>'xyz.jpg', 'name'=>'3 Inch 6 round square pieces edible cookie images', 'description'=>'Round square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_round_square.png', 'make'=>'6', 'img'=>'6_round_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH075', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'11', 'size_id'=>'1', 'alias_name'=>'2.25', 'alias_img'=>'xyz.jpg', 'name'=>'2.25 Inch 8 round square pieces edible size images', 'description'=>'Round square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_round_square.png', 'make'=>'8', 'img'=>'8_round_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH076', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'11', 'size_id'=>'1', 'alias_name'=>'2', 'alias_img'=>'xyz.jpg', 'name'=>'2 Inch 12 round square pieces edible cupcake Images', 'description'=>'Round square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_round_square.png', 'make'=>'12', 'img'=>'12_round_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH077', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'11', 'size_id'=>'1', 'alias_name'=>'1.5', 'alias_img'=>'xyz.jpg', 'name'=>'1.5 Inch 24 round square pieces edible cupcake Images', 'description'=>'Round square shape edible decoration print for cakes. High quality edible paper (frosting sheet) bright high resolution food coloring.', 'file'=>'7inch_round_square.png', 'make'=>'24', 'img'=>'24_round_square_pieces.jpg', 'type'=>'1', 'link'=>'html', 'sku'=>'CH078', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.jpg', 'name'=>'Happy Birthday & Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'1.png', 'make'=>'1', 'img'=>'1.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH079', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.jpg', 'name'=>'Green Frame & Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'2.png', 'make'=>'1', 'img'=>'2.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH080', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.jpg', 'name'=>'Yellow Candy Birthday', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'3.png', 'make'=>'1', 'img'=>'3.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH081', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Yellow Brown and Red Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'4.png', 'make'=>'1', 'img'=>'4.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH082', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Green and Read Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'5.png', 'make'=>'1', 'img'=>'5.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH083', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Flying Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'6.png', 'make'=>'1', 'img'=>'6.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH084', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Balloons Pool', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'7.png', 'make'=>'1', 'img'=>'7.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH085', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Monogram Balloons Frame', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'8.png', 'make'=>'1', 'img'=>'8.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH086', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Birthday Star Yellow Frame', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'9.png', 'make'=>'1', 'img'=>'9.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH087', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Rainbow Heart & Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'10.png', 'make'=>'1', 'img'=>'10.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH088', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Star and Rainbow Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'11.png', 'make'=>'1', 'img'=>'11.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH089', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Corner Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'12.png', 'make'=>'1', 'img'=>'12.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH090', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Cake and Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'13.png', 'make'=>'1', 'img'=>'13.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH091', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'American Cake & Balloons', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'14.png', 'make'=>'1', 'img'=>'14.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH092', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Pink Party Cake', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'15.png', 'make'=>'1', 'img'=>'15.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH093', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Pastries & Gifts', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'16.png', 'make'=>'1', 'img'=>'16.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH094', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Tier Cake Frame', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'17.png', 'make'=>'1', 'img'=>'17.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH095', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Balloon & Red Birthday', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'18.png', 'make'=>'1', 'img'=>'18.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH096', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Flowers & Window Birthday', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'19.png', 'make'=>'1', 'img'=>'19.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH097', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],
['cat_id'=>'12', 'size_id'=>'1', 'alias_name'=>'10x7.5', 'alias_img'=>'xyz.png', 'name'=>'Stage Birthday', 'description'=>'Customizable cake border decoration for ¼ sheet  half sheet and other pastries. High quality edible paper (frosting sheet) printed with bright food coloring at 300 dpi for high resolution.', 'file'=>'20.png', 'make'=>'1', 'img'=>'20.png', 'type'=>'1', 'link'=>'html', 'sku'=>'CH098', 'price'=>'5.99', 'upc'=>'680474308972', 'brand'=>'CKHO', 'weight'=>'0.2', 'width'=>'10','height'=>'7.5', 'condition'=>'new', 'ingredients'=>'Tapioca Starch Corn Syrup Solids Microcrystalline Cellulose Sugar Water Glycerine Canola Oil Polyglycerol Esters Titanium Dioxide Algin Potassium Sorbate Citric Acid Sodium Bicarbonate Soy Lecithin.'],



// other starts here///


// //  Rectangles
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Dark City', 'description'=>'New York City buiding close up, Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'21.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'At the Sea', 'description'=>'From the Iron man scene and poster, Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'22.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Car Explosion', 'description'=>'Nicolas Cage walking away from a blast, Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'23.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Motorcycle Get Away', 'description'=>'Cameron Diaz & Tom Cruz getting away on a motorcycle, Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'24.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Mechanical Suit', 'description'=>'2014 Robo Cop mechanical suit face mask Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'25.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Mechanical Face', 'description'=>'Robot cop close up face mask Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'26.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Warrior', 'description'=>'Conan the barbarian Arnold Schwarzenegger face mask Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'27.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Cop Action', 'description'=>'Get away cop car / cruizer Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'28.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Sky Diving', 'description'=>'Skydivers face mask Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'29.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Detective', 'description'=>'Men in black face mask Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'30.png', 'make'=>'1'],,
// ['cat_id'=>'5', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Space Suit', 'description'=>'Space suit head shot Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet', 'file'=>'31.png', 'make'=>'1'],,


// // Halloween
// ['cat_id'=>'6', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'The Walking Dead Edible Images', 'description'=>'The Walking Dead Edible Images Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet <br> <strong>Upload Instructions: </strong> <a href="/halloween_2014">Halloween Movie Cake Instructions </a>', 'file'=>'32.png', 'make'=>'1'],,
// ['cat_id'=>'6', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Freddy Krueger VS Zombies', 'description'=>'Freddy Krueger VS Zombies Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet <br> <strong>Upload Instructions: </strong> <a href="/halloween_2014">Halloween Movie Cake Instructions </a>', 'file'=>'33.png', 'make'=>'1'],,
// ['cat_id'=>'6', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Zombie Corp', 'description'=>'Corporations make you turn in to a Zombie Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet <br> <strong>Upload Instructions: </strong> <a href="/halloween_2014">Halloween Movie Cake Instructions </a>', 'file'=>'34.png', 'make'=>'1'],,
// ['cat_id'=>'6', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'The Exorcist Returns', 'description'=>'Signs of Demonic Possession Edible Cake Image Border <br> <strong>Usage:</strong> Rectangle Cakes <br><strong>Size:</strong> 10x7.5 Standar 1/4 Sheet  <br> <strong>Material:</strong> High Quality Sugar Sheet <br> <strong>Upload Instructions: </strong> <a href="/halloween_2014">Halloween Movie Cake Instructions </a>', 'file'=>'35.png', 'make'=>'1'],,


// // // Halloween Rectangle
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Pirates Skull', 'description'=>'Birthday Border 1', 'file'=>'r-skull1.png', 'make'=>'1'],,
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Little Girl Pink Hair Skull', 'description'=>'Birthday Border 2', 'file'=>'r-skull2.png', 'make'=>'1'],,
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Color Flower Skulls', 'description'=>'Birthday Border 3', 'file'=>'r-skull3.png', 'make'=>'1'],,
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'86 Kull made of Skulls', 'description'=>'Birthday Border 4', 'file'=>'r-skull4.png', 'make'=>'1'],,
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Many Skulls', 'description'=>'Birthday Border 5', 'file'=>'r-skull5.png', 'make'=>'1'],,
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Big Skull', 'description'=>'Birthday Border 5', 'file'=>'r-skull6.png', 'make'=>'1'],,
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Hipi Skull', 'description'=>'Birthday Border 5', 'file'=>'r-skull7.png', 'make'=>'1'],,
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Skull on Fire', 'description'=>'Birthday Border 5', 'file'=>'r-skull8.png', 'make'=>'1'],,
// ['cat_id'=>'7', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Pink Bow Skull', 'description'=>'Birthday Border 5', 'file'=>'r-skull9.png', 'make'=>'1'],,
// // Halloween Round
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Pirates Skull', 'description'=>'Birthday Border 1', 'file'=>'c-skull1.png', 'make'=>'1'],,
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Little Girl Pink Hair Skull', 'description'=>'Birthday Border 2', 'file'=>'c-skull2.png', 'make'=>'1'],,
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Color Flower Skulls', 'description'=>'Birthday Border 3', 'file'=>'c-skull3.png', 'make'=>'1'],,
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'86 Kull made of Skulls', 'description'=>'Birthday Border 4', 'file'=>'c-skull4.png', 'make'=>'1'],,
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Many Skulls', 'description'=>'Birthday Border 5', 'file'=>'c-skull5.png', 'make'=>'1'],,
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Big Skull', 'description'=>'Birthday Border 5', 'file'=>'c-skull6.png', 'make'=>'1'],,
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Hipi Skull', 'description'=>'Birthday Border 5', 'file'=>'c-skull7.png', 'make'=>'1'],,
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Skull on Fire', 'description'=>'Birthday Border 5', 'file'=>'c-skull8.png', 'make'=>'1'],,
// ['cat_id'=>'8', 'size_id'=>'1', 'alias_name'=>'xyz', 'alias_img'=>'xyz.jpg', 'name'=>'Pink Bow Skull', 'description'=>'Birthday Border 5', 'file'=>'c-skull9.png', 'make'=>'1'],,

		);

		// Uncomment the below to run the seeder
		 DB::table('borders')->insert($items);
	}

}